apiVersion: v1
kind: Service
metadata:
  name: react-app-service  # Make the service name more descriptive
spec:
  selector:
    app: react-app         # Ensure this matches the 'app' label in your Deployment
  type: NodePort       # This will provision an external LoadBalancer
  ports:
  - name: http
    port: 80              # Port on which the service will be accessible
    targetPort: 3000      # Port where your application is listening inside the container
    nodePort: 30080
